{{- include "nexorious.validateValues" . }}
{{- $omitDbUrl := or .Values.nexorious.databaseUrlFrom.name .Values.nexorious.dbHostFrom.name .Values.nexorious.dbPortFrom.name .Values.nexorious.dbUserFrom.name .Values.nexorious.dbPasswordFrom.name .Values.nexorious.dbNameFrom.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexorious.credentialsSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "nexorious.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
{{- if not .Values.nexorious.secretKeyFrom.name }}
  SECRET_KEY: {{ .Values.nexorious.secretKey | quote }}
{{- end }}
{{- if not .Values.nexorious.internalApiKeyFrom.name }}
  INTERNAL_API_KEY: {{ .Values.nexorious.internalApiKey | quote }}
{{- end }}
{{- if not .Values.nexorious.igdbClientIdFrom.name }}
  IGDB_CLIENT_ID: {{ .Values.nexorious.igdbClientId | quote }}
{{- end }}
{{- if not .Values.nexorious.igdbClientSecretFrom.name }}
  IGDB_CLIENT_SECRET: {{ .Values.nexorious.igdbClientSecret | quote }}
{{- end }}
  POSTGRES_PASSWORD: {{ .Values.nexorious.postgresql.password | quote }}
{{- if not $omitDbUrl }}
  DATABASE_URL: {{ include "nexorious.databaseUrl" . | quote }}
{{- end }}
  NATS_URL: {{ include "nexorious.natsUrl" . | quote }}
  INTERNAL_API_URL: {{ include "nexorious.internalApiUrl" . | quote }}
