{{- include "nexorious.validateValues" . }}
{{- $databaseUrlFrom := default dict .Values.nexorious.databaseUrlFrom }}
{{- $dbHostFrom := default dict .Values.nexorious.dbHostFrom }}
{{- $dbPortFrom := default dict .Values.nexorious.dbPortFrom }}
{{- $dbUserFrom := default dict .Values.nexorious.dbUserFrom }}
{{- $dbPasswordFrom := default dict .Values.nexorious.dbPasswordFrom }}
{{- $dbNameFrom := default dict .Values.nexorious.dbNameFrom }}
{{- $secretKeyFrom := default dict .Values.nexorious.secretKeyFrom }}
{{- $igdbClientIdFrom := default dict .Values.nexorious.igdbClientIdFrom }}
{{- $igdbClientSecretFrom := default dict .Values.nexorious.igdbClientSecretFrom }}
{{- $omitDbUrl := or $databaseUrlFrom.name $dbHostFrom.name $dbPortFrom.name $dbUserFrom.name $dbPasswordFrom.name $dbNameFrom.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexorious.credentialsSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "nexorious.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
{{- if not $secretKeyFrom.name }}
  SECRET_KEY: {{ .Values.nexorious.secretKey | quote }}
{{- end }}
{{- if not $igdbClientIdFrom.name }}
  IGDB_CLIENT_ID: {{ .Values.nexorious.igdbClientId | quote }}
{{- end }}
{{- if not $igdbClientSecretFrom.name }}
  IGDB_CLIENT_SECRET: {{ .Values.nexorious.igdbClientSecret | quote }}
{{- end }}
{{- if dig "postgresql" "enabled" true .Values.controllers }}
  POSTGRES_PASSWORD: {{ .Values.nexorious.postgresql.password | quote }}
{{- end }}
{{- if not $omitDbUrl }}
  DATABASE_URL: {{ include "nexorious.databaseUrl" . | quote }}
{{- end }}
