// psprices region codes (ISO 3166-1 alpha-2), kept in sync with the backend
// allowlist in internal/dealregion. Labels are display-only.
export const DEAL_REGIONS: { code: string; label: string }[] = [
  { code: 'us', label: 'United States' },
  { code: 'gb', label: 'United Kingdom' },
  { code: 'au', label: 'Australia' },
  { code: 'ca', label: 'Canada' },
  { code: 'de', label: 'Germany' },
  { code: 'fr', label: 'France' },
  { code: 'es', label: 'Spain' },
  { code: 'it', label: 'Italy' },
  { code: 'nl', label: 'Netherlands' },
  { code: 'pt', label: 'Portugal' },
  { code: 'pl', label: 'Poland' },
  { code: 'se', label: 'Sweden' },
  { code: 'no', label: 'Norway' },
  { code: 'dk', label: 'Denmark' },
  { code: 'fi', label: 'Finland' },
  { code: 'ie', label: 'Ireland' },
  { code: 'jp', label: 'Japan' },
  { code: 'kr', label: 'South Korea' },
  { code: 'hk', label: 'Hong Kong' },
  { code: 'tw', label: 'Taiwan' },
  { code: 'sg', label: 'Singapore' },
  { code: 'br', label: 'Brazil' },
  { code: 'mx', label: 'Mexico' },
  { code: 'ar', label: 'Argentina' },
  { code: 'za', label: 'South Africa' },
  { code: 'in', label: 'India' },
  { code: 'nz', label: 'New Zealand' },
];
