/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryHealthRouteImport } from './routes/_authenticated/library-health'
import { Route as AuthenticatedImportExportRouteImport } from './routes/_authenticated/import-export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSyncIndexRouteImport } from './routes/_authenticated/sync/index'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated/pools/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSyncStorefrontRouteImport } from './routes/_authenticated/sync/$storefront'
import { Route as AuthenticatedPoolsIdRouteImport } from './routes/_authenticated/pools/$id'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs/$id'
import { Route as AuthenticatedHelpSlugRouteImport } from './routes/_authenticated/help/$slug'
import { Route as AuthenticatedGamesAddRouteImport } from './routes/_authenticated/games/add'
import { Route as AuthenticatedGamesIdRouteImport } from './routes/_authenticated/games/$id'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin/maintenance'
import { Route as AuthenticatedAdminBackupsRouteImport } from './routes/_authenticated/admin/backups'
import { Route as AuthenticatedGamesAddIndexRouteImport } from './routes/_authenticated/games/add.index'
import { Route as AuthenticatedGamesIdIndexRouteImport } from './routes/_authenticated/games/$id.index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminActivityIndexRouteImport } from './routes/_authenticated/admin/activity/index'
import { Route as AuthenticatedGamesAddConfirmRouteImport } from './routes/_authenticated/games/add.confirm'
import { Route as AuthenticatedGamesIdEditRouteImport } from './routes/_authenticated/games/$id.edit'
import { Route as AuthenticatedAdminUsersNewRouteImport } from './routes/_authenticated/admin/users/new'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryHealthRoute =
  AuthenticatedLibraryHealthRouteImport.update({
    id: '/library-health',
    path: '/library-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportExportRoute =
  AuthenticatedImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncIndexRoute = AuthenticatedSyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncStorefrontRoute =
  AuthenticatedSyncStorefrontRouteImport.update({
    id: '/sync/$storefront',
    path: '/sync/$storefront',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoolsIdRoute = AuthenticatedPoolsIdRouteImport.update({
  id: '/pools/$id',
  path: '/pools/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpSlugRoute = AuthenticatedHelpSlugRouteImport.update({
  id: '/help/$slug',
  path: '/help/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesAddRoute = AuthenticatedGamesAddRouteImport.update({
  id: '/games/add',
  path: '/games/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesIdRoute = AuthenticatedGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/admin/maintenance',
    path: '/admin/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBackupsRoute =
  AuthenticatedAdminBackupsRouteImport.update({
    id: '/admin/backups',
    path: '/admin/backups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesAddIndexRoute =
  AuthenticatedGamesAddIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGamesAddRoute,
  } as any)
const AuthenticatedGamesIdIndexRoute =
  AuthenticatedGamesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGamesIdRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminActivityIndexRoute =
  AuthenticatedAdminActivityIndexRouteImport.update({
    id: '/admin/activity/',
    path: '/admin/activity/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesAddConfirmRoute =
  AuthenticatedGamesAddConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => AuthenticatedGamesAddRoute,
  } as any)
const AuthenticatedGamesIdEditRoute =
  AuthenticatedGamesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedGamesIdRoute,
  } as any)
const AuthenticatedAdminUsersNewRoute =
  AuthenticatedAdminUsersNewRouteImport.update({
    id: '/admin/users/new',
    path: '/admin/users/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/library-health': typeof AuthenticatedLibraryHealthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/login': typeof PublicLoginRoute
  '/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/games/$id': typeof AuthenticatedGamesIdRouteWithChildren
  '/games/add': typeof AuthenticatedGamesAddRouteWithChildren
  '/help/$slug': typeof AuthenticatedHelpSlugRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/pools/$id': typeof AuthenticatedPoolsIdRoute
  '/sync/$storefront': typeof AuthenticatedSyncStorefrontRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
  '/sync/': typeof AuthenticatedSyncIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/games/$id/edit': typeof AuthenticatedGamesIdEditRoute
  '/games/add/confirm': typeof AuthenticatedGamesAddConfirmRoute
  '/admin/activity/': typeof AuthenticatedAdminActivityIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/games/$id/': typeof AuthenticatedGamesIdIndexRoute
  '/games/add/': typeof AuthenticatedGamesAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/library-health': typeof AuthenticatedLibraryHealthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/login': typeof PublicLoginRoute
  '/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/help/$slug': typeof AuthenticatedHelpSlugRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/pools/$id': typeof AuthenticatedPoolsIdRoute
  '/sync/$storefront': typeof AuthenticatedSyncStorefrontRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
  '/sync': typeof AuthenticatedSyncIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/games/$id/edit': typeof AuthenticatedGamesIdEditRoute
  '/games/add/confirm': typeof AuthenticatedGamesAddConfirmRoute
  '/admin/activity': typeof AuthenticatedAdminActivityIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/games/$id': typeof AuthenticatedGamesIdIndexRoute
  '/games/add': typeof AuthenticatedGamesAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import-export': typeof AuthenticatedImportExportRoute
  '/_authenticated/library-health': typeof AuthenticatedLibraryHealthRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/_public/login': typeof PublicLoginRoute
  '/_authenticated/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/games/$id': typeof AuthenticatedGamesIdRouteWithChildren
  '/_authenticated/games/add': typeof AuthenticatedGamesAddRouteWithChildren
  '/_authenticated/help/$slug': typeof AuthenticatedHelpSlugRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/pools/$id': typeof AuthenticatedPoolsIdRoute
  '/_authenticated/sync/$storefront': typeof AuthenticatedSyncStorefrontRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
  '/_authenticated/sync/': typeof AuthenticatedSyncIndexRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/_authenticated/games/$id/edit': typeof AuthenticatedGamesIdEditRoute
  '/_authenticated/games/add/confirm': typeof AuthenticatedGamesAddConfirmRoute
  '/_authenticated/admin/activity/': typeof AuthenticatedAdminActivityIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/games/$id/': typeof AuthenticatedGamesIdIndexRoute
  '/_authenticated/games/add/': typeof AuthenticatedGamesAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/import-export'
    | '/library-health'
    | '/profile'
    | '/review'
    | '/tags'
    | '/wishlist'
    | '/login'
    | '/admin/backups'
    | '/admin/maintenance'
    | '/games/$id'
    | '/games/add'
    | '/help/$slug'
    | '/jobs/$id'
    | '/pools/$id'
    | '/sync/$storefront'
    | '/admin/'
    | '/games/'
    | '/jobs/'
    | '/pools/'
    | '/sync/'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/games/$id/edit'
    | '/games/add/confirm'
    | '/admin/activity/'
    | '/admin/users/'
    | '/games/$id/'
    | '/games/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/import-export'
    | '/library-health'
    | '/profile'
    | '/review'
    | '/tags'
    | '/wishlist'
    | '/login'
    | '/admin/backups'
    | '/admin/maintenance'
    | '/help/$slug'
    | '/jobs/$id'
    | '/pools/$id'
    | '/sync/$storefront'
    | '/admin'
    | '/games'
    | '/jobs'
    | '/pools'
    | '/sync'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/games/$id/edit'
    | '/games/add/confirm'
    | '/admin/activity'
    | '/admin/users'
    | '/games/$id'
    | '/games/add'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_authenticated/import-export'
    | '/_authenticated/library-health'
    | '/_authenticated/profile'
    | '/_authenticated/review'
    | '/_authenticated/tags'
    | '/_authenticated/wishlist'
    | '/_public/login'
    | '/_authenticated/admin/backups'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/games/$id'
    | '/_authenticated/games/add'
    | '/_authenticated/help/$slug'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/pools/$id'
    | '/_authenticated/sync/$storefront'
    | '/_authenticated/admin/'
    | '/_authenticated/games/'
    | '/_authenticated/jobs/'
    | '/_authenticated/pools/'
    | '/_authenticated/sync/'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/admin/users/new'
    | '/_authenticated/games/$id/edit'
    | '/_authenticated/games/add/confirm'
    | '/_authenticated/admin/activity/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/games/$id/'
    | '/_authenticated/games/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library-health': {
      id: '/_authenticated/library-health'
      path: '/library-health'
      fullPath: '/library-health'
      preLoaderRoute: typeof AuthenticatedLibraryHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import-export': {
      id: '/_authenticated/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthenticatedImportExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync/': {
      id: '/_authenticated/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof AuthenticatedSyncIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync/$storefront': {
      id: '/_authenticated/sync/$storefront'
      path: '/sync/$storefront'
      fullPath: '/sync/$storefront'
      preLoaderRoute: typeof AuthenticatedSyncStorefrontRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/$id': {
      id: '/_authenticated/pools/$id'
      path: '/pools/$id'
      fullPath: '/pools/$id'
      preLoaderRoute: typeof AuthenticatedPoolsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help/$slug': {
      id: '/_authenticated/help/$slug'
      path: '/help/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof AuthenticatedHelpSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/add': {
      id: '/_authenticated/games/add'
      path: '/games/add'
      fullPath: '/games/add'
      preLoaderRoute: typeof AuthenticatedGamesAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/$id': {
      id: '/_authenticated/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AuthenticatedGamesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/backups': {
      id: '/_authenticated/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AuthenticatedAdminBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/add/': {
      id: '/_authenticated/games/add/'
      path: '/'
      fullPath: '/games/add/'
      preLoaderRoute: typeof AuthenticatedGamesAddIndexRouteImport
      parentRoute: typeof AuthenticatedGamesAddRoute
    }
    '/_authenticated/games/$id/': {
      id: '/_authenticated/games/$id/'
      path: '/'
      fullPath: '/games/$id/'
      preLoaderRoute: typeof AuthenticatedGamesIdIndexRouteImport
      parentRoute: typeof AuthenticatedGamesIdRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/activity/': {
      id: '/_authenticated/admin/activity/'
      path: '/admin/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AuthenticatedAdminActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/add/confirm': {
      id: '/_authenticated/games/add/confirm'
      path: '/confirm'
      fullPath: '/games/add/confirm'
      preLoaderRoute: typeof AuthenticatedGamesAddConfirmRouteImport
      parentRoute: typeof AuthenticatedGamesAddRoute
    }
    '/_authenticated/games/$id/edit': {
      id: '/_authenticated/games/$id/edit'
      path: '/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof AuthenticatedGamesIdEditRouteImport
      parentRoute: typeof AuthenticatedGamesIdRoute
    }
    '/_authenticated/admin/users/new': {
      id: '/_authenticated/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedGamesIdRouteChildren {
  AuthenticatedGamesIdEditRoute: typeof AuthenticatedGamesIdEditRoute
  AuthenticatedGamesIdIndexRoute: typeof AuthenticatedGamesIdIndexRoute
}

const AuthenticatedGamesIdRouteChildren: AuthenticatedGamesIdRouteChildren = {
  AuthenticatedGamesIdEditRoute: AuthenticatedGamesIdEditRoute,
  AuthenticatedGamesIdIndexRoute: AuthenticatedGamesIdIndexRoute,
}

const AuthenticatedGamesIdRouteWithChildren =
  AuthenticatedGamesIdRoute._addFileChildren(AuthenticatedGamesIdRouteChildren)

interface AuthenticatedGamesAddRouteChildren {
  AuthenticatedGamesAddConfirmRoute: typeof AuthenticatedGamesAddConfirmRoute
  AuthenticatedGamesAddIndexRoute: typeof AuthenticatedGamesAddIndexRoute
}

const AuthenticatedGamesAddRouteChildren: AuthenticatedGamesAddRouteChildren = {
  AuthenticatedGamesAddConfirmRoute: AuthenticatedGamesAddConfirmRoute,
  AuthenticatedGamesAddIndexRoute: AuthenticatedGamesAddIndexRoute,
}

const AuthenticatedGamesAddRouteWithChildren =
  AuthenticatedGamesAddRoute._addFileChildren(
    AuthenticatedGamesAddRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportExportRoute: typeof AuthenticatedImportExportRoute
  AuthenticatedLibraryHealthRoute: typeof AuthenticatedLibraryHealthRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedAdminBackupsRoute: typeof AuthenticatedAdminBackupsRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedGamesIdRoute: typeof AuthenticatedGamesIdRouteWithChildren
  AuthenticatedGamesAddRoute: typeof AuthenticatedGamesAddRouteWithChildren
  AuthenticatedHelpSlugRoute: typeof AuthenticatedHelpSlugRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
  AuthenticatedPoolsIdRoute: typeof AuthenticatedPoolsIdRoute
  AuthenticatedSyncStorefrontRoute: typeof AuthenticatedSyncStorefrontRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
  AuthenticatedSyncIndexRoute: typeof AuthenticatedSyncIndexRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersNewRoute: typeof AuthenticatedAdminUsersNewRoute
  AuthenticatedAdminActivityIndexRoute: typeof AuthenticatedAdminActivityIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportExportRoute: AuthenticatedImportExportRoute,
  AuthenticatedLibraryHealthRoute: AuthenticatedLibraryHealthRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedAdminBackupsRoute: AuthenticatedAdminBackupsRoute,
  AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
  AuthenticatedGamesIdRoute: AuthenticatedGamesIdRouteWithChildren,
  AuthenticatedGamesAddRoute: AuthenticatedGamesAddRouteWithChildren,
  AuthenticatedHelpSlugRoute: AuthenticatedHelpSlugRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
  AuthenticatedPoolsIdRoute: AuthenticatedPoolsIdRoute,
  AuthenticatedSyncStorefrontRoute: AuthenticatedSyncStorefrontRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
  AuthenticatedSyncIndexRoute: AuthenticatedSyncIndexRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminUsersNewRoute: AuthenticatedAdminUsersNewRoute,
  AuthenticatedAdminActivityIndexRoute: AuthenticatedAdminActivityIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
