"""Add default storefront relationship to platforms

Revision ID: 02fe85fd9ec7
Revises: a1bbb8869bf3
Create Date: 2025-07-28 06:26:55.653007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02fe85fd9ec7'
down_revision: Union[str, Sequence[str], None] = 'a1bbb8869bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_platforms_default_storefront_id', 'storefronts', ['default_storefront_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_platforms_default_storefront_id', type_='foreignkey')
        batch_op.drop_column('default_storefront_id')
    # ### end Alembic commands ###
