"""Add igdb_platform_ids field to games table

Revision ID: 3b8062b0037d
Revises: 2ef4c8daba74
Create Date: 2025-07-29 14:07:09.343670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b8062b0037d'
down_revision: Union[str, Sequence[str], None] = '2ef4c8daba74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('igdb_platform_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'igdb_platform_ids')
    # ### end Alembic commands ###
