"""add updated_at field to user_game_platforms table

Revision ID: 403047671e7b
Revises: a11a9ee5095a
Create Date: 2025-07-24 17:11:04.155203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403047671e7b'
down_revision: Union[str, Sequence[str], None] = 'a11a9ee5095a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding NOT NULL columns with function defaults
    # Add the column as nullable first, then update and make NOT NULL
    op.add_column('user_game_platforms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # Update existing rows to use created_at value for updated_at
    op.execute("UPDATE user_game_platforms SET updated_at = created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_platforms', 'updated_at')
    # ### end Alembic commands ###
