"""remove is_verified field from games table

Revision ID: 5992945f2998
Revises: ffc5e4f1d8e2
Create Date: 2025-08-03 04:59:50.547659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5992945f2998'
down_revision: Union[str, Sequence[str], None] = 'ffc5e4f1d8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
