"""Remove physical fields from user_games table

Revision ID: 5d4811469120
Revises: 02fe85fd9ec7
Create Date: 2025-07-28 06:42:01.569011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4811469120'
down_revision: Union[str, Sequence[str], None] = '02fe85fd9ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_games', 'physical_location')
    op.drop_column('user_games', 'is_physical')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_games', sa.Column('is_physical', sa.BOOLEAN(), nullable=False))
    op.add_column('user_games', sa.Column('physical_location', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
