"""Add igdb_slug field to games table

Revision ID: 5eaf19101a5a
Revises: 3b8062b0037d
Create Date: 2025-07-29 20:29:12.728140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5eaf19101a5a'
down_revision: Union[str, Sequence[str], None] = '3b8062b0037d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('igdb_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.create_index(op.f('ix_games_igdb_slug'), 'games', ['igdb_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_igdb_slug'), table_name='games')
    op.drop_column('games', 'igdb_slug')
    # ### end Alembic commands ###
