"""Add igdb_platform_names field to games table

Revision ID: 68af15b2b34b
Revises: 5eaf19101a5a
Create Date: 2025-07-30 07:25:49.390362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68af15b2b34b'
down_revision: Union[str, Sequence[str], None] = '5eaf19101a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('igdb_platform_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'igdb_platform_names')
    # ### end Alembic commands ###
