"""Add source and version_added fields to platforms and storefronts

Revision ID: 8d2e10413b18
Revises: 403047671e7b
Create Date: 2025-07-25 08:38:54.445321

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d2e10413b18'
down_revision: Union[str, Sequence[str], None] = '403047671e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and seed official platforms/storefronts."""
    # Check if columns already exist before adding them (for idempotency)
    connection = op.get_bind()
    
    # Check and add platforms columns
    try:
        platforms_info = connection.execute(sa.text("PRAGMA table_info(platforms)")).fetchall()
        existing_columns = [col[1] for col in platforms_info]
        
        if 'source' not in existing_columns:
            op.add_column('platforms', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='custom'))
        if 'version_added' not in existing_columns:
            op.add_column('platforms', sa.Column('version_added', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    except Exception as e:
        # If pragma fails, try adding columns anyway - let it fail if they exist
        try:
            op.add_column('platforms', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='custom'))
        except:
            pass
        try:
            op.add_column('platforms', sa.Column('version_added', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
        except:
            pass
    
    # Check and add storefronts columns
    try:
        storefronts_info = connection.execute(sa.text("PRAGMA table_info(storefronts)")).fetchall()
        existing_columns = [col[1] for col in storefronts_info]
        
        if 'source' not in existing_columns:
            op.add_column('storefronts', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='custom'))
        if 'version_added' not in existing_columns:
            op.add_column('storefronts', sa.Column('version_added', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    except Exception as e:
        # If pragma fails, try adding columns anyway - let it fail if they exist
        try:
            op.add_column('storefronts', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='custom'))
        except:
            pass
        try:
            op.add_column('storefronts', sa.Column('version_added', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
        except:
            pass
    
    # Seed official platforms and storefronts
    _seed_official_data()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storefronts', 'version_added')
    op.drop_column('storefronts', 'source')
    op.drop_column('platforms', 'version_added')
    op.drop_column('platforms', 'source')
    # Skip the problematic ALTER COLUMN operation for SQLite compatibility
    # ### end Alembic commands ###


def _seed_official_data() -> None:
    """Seed official platforms and storefronts with conflict resolution."""
    connection = op.get_bind()
    
    # Official platforms data
    official_platforms = [
        {
            "id": str(uuid.uuid4()),
            "name": "pc",
            "display_name": "PC",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "playstation-4",
            "display_name": "PlayStation 4",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "playstation-5",
            "display_name": "PlayStation 5",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "xbox-one",
            "display_name": "Xbox One",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "xbox-series",
            "display_name": "Xbox Series X/S",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "nintendo-switch",
            "display_name": "Nintendo Switch",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "ios",
            "display_name": "iOS",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "android",
            "display_name": "Android",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "nintendo-3ds",
            "display_name": "Nintendo 3DS",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "playstation-vita",
            "display_name": "PlayStation Vita",
            "icon_url": None,
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        }
    ]
    
    # Official storefronts data
    official_storefronts = [
        {
            "id": str(uuid.uuid4()),
            "name": "steam",
            "display_name": "Steam",
            "icon_url": None,
            "base_url": "https://store.steampowered.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "epic-games-store",
            "display_name": "Epic Games Store",
            "icon_url": None,
            "base_url": "https://store.epicgames.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "gog",
            "display_name": "GOG",
            "icon_url": None,
            "base_url": "https://www.gog.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "microsoft-store",
            "display_name": "Microsoft Store",
            "icon_url": None,
            "base_url": "https://www.microsoft.com/store",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "origin",
            "display_name": "Origin",
            "icon_url": None,
            "base_url": "https://www.origin.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "battle-net",
            "display_name": "Battle.net",
            "icon_url": None,
            "base_url": "https://us.shop.battle.net",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "ubisoft-connect",
            "display_name": "Ubisoft Connect",
            "icon_url": None,
            "base_url": "https://store.ubisoft.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "playstation-store",
            "display_name": "PlayStation Store",
            "icon_url": None,
            "base_url": "https://store.playstation.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "nintendo-eshop",
            "display_name": "Nintendo eShop",
            "icon_url": None,
            "base_url": "https://www.nintendo.com/us/store",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "app-store",
            "display_name": "App Store",
            "icon_url": None,
            "base_url": "https://apps.apple.com",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        },
        {
            "id": str(uuid.uuid4()),
            "name": "google-play",
            "display_name": "Google Play Store",
            "icon_url": None,
            "base_url": "https://play.google.com/store",
            "is_active": True,
            "source": "official",
            "version_added": "1.0.0",
            "created_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc)
        }
    ]
    
    # Insert platforms with conflict resolution
    for platform_data in official_platforms:
        # Check if platform with same name already exists
        existing_platform = connection.execute(
            sa.text("SELECT id, source FROM platforms WHERE name = :name"),
            {"name": platform_data["name"]}
        ).fetchone()
        
        if existing_platform:
            # If it's a custom platform, update it to official
            if existing_platform[1] == "custom":
                connection.execute(
                    sa.text("""
                        UPDATE platforms 
                        SET source = :source, version_added = :version_added, updated_at = :updated_at
                        WHERE id = :id
                    """),
                    {
                        "source": platform_data["source"],
                        "version_added": platform_data["version_added"],
                        "updated_at": platform_data["updated_at"],
                        "id": existing_platform[0]
                    }
                )
        else:
            # Insert new official platform
            connection.execute(
                sa.text("""
                    INSERT INTO platforms (id, name, display_name, icon_url, is_active, source, version_added, created_at, updated_at)
                    VALUES (:id, :name, :display_name, :icon_url, :is_active, :source, :version_added, :created_at, :updated_at)
                """),
                platform_data
            )
    
    # Insert storefronts with conflict resolution
    for storefront_data in official_storefronts:
        # Check if storefront with same name already exists
        existing_storefront = connection.execute(
            sa.text("SELECT id, source FROM storefronts WHERE name = :name"),
            {"name": storefront_data["name"]}
        ).fetchone()
        
        if existing_storefront:
            # If it's a custom storefront, update it to official
            if existing_storefront[1] == "custom":
                connection.execute(
                    sa.text("""
                        UPDATE storefronts 
                        SET source = :source, version_added = :version_added, updated_at = :updated_at
                        WHERE id = :id
                    """),
                    {
                        "source": storefront_data["source"],
                        "version_added": storefront_data["version_added"], 
                        "updated_at": storefront_data["updated_at"],
                        "id": existing_storefront[0]
                    }
                )
        else:
            # Insert new official storefront
            connection.execute(
                sa.text("""
                    INSERT INTO storefronts (id, name, display_name, icon_url, base_url, is_active, source, version_added, created_at, updated_at)
                    VALUES (:id, :name, :display_name, :icon_url, :base_url, :is_active, :source, :version_added, :created_at, :updated_at)
                """),
                storefront_data
            )
