"""Add unique constraint to user_game_platforms for multiple storefronts per platform

Revision ID: 9e80e256522d
Revises: 5d4811469120
Create Date: 2025-07-28 06:49:27.618024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e80e256522d'
down_revision: Union[str, Sequence[str], None] = '5d4811469120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_platforms', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_game_platform_storefront', ['user_game_id', 'platform_id', 'storefront_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_platforms', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_game_platform_storefront', type_='unique')
    # ### end Alembic commands ###
