"""Remove first_name and last_name columns from users table

Revision ID: a11a9ee5095a
Revises: dd3d15b335d7
Create Date: 2025-07-16 17:18:29.285458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11a9ee5095a'
down_revision: Union[str, Sequence[str], None] = 'dd3d15b335d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
