"""Add updated_at field to UserSession model

Revision ID: dd3d15b335d7
Revises: a969927ae43f
Create Date: 2025-07-16 11:41:03.039805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3d15b335d7'
down_revision: Union[str, Sequence[str], None] = 'a969927ae43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'updated_at')
    # ### end Alembic commands ###
