"""Add platform_storefronts junction table for many-to-many associations

Revision ID: ffc5e4f1d8e2
Revises: 12c1f1727159
Create Date: 2025-08-01 19:38:06.765811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffc5e4f1d8e2'
down_revision: Union[str, Sequence[str], None] = '12c1f1727159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_storefronts',
    sa.Column('platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], ),
    sa.PrimaryKeyConstraint('platform_id', 'storefront_id'),
    sa.UniqueConstraint('platform_id', 'storefront_id', name='uq_platform_storefront')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_storefronts')
    # ### end Alembic commands ###
