"""add platform_credentials to user_sync_configs

Revision ID: 0c863acf2282
Revises: 972c3d4ae063
Create Date: 2026-01-01 00:02:35.162354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c863acf2282'
down_revision: Union[str, Sequence[str], None] = '972c3d4ae063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sync_configs', sa.Column('platform_credentials', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sync_configs', 'platform_credentials')
    # ### end Alembic commands ###
