"""Add external_games table

Revision ID: 1531bea008ab
Revises: 16859bc970d4
Create Date: 2026-02-28 19:08:58.020958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1531bea008ab'
down_revision: Union[str, Sequence[str], None] = '16859bc970d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create table without ownership_status to avoid re-creating the existing
    # ownershipstatus enum type (op.create_table fires after_create events).
    op.create_table('external_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storefront', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('resolved_igdb_id', sa.Integer(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('playtime_hours', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform'], ['platforms.name'], ),
    sa.ForeignKeyConstraint(['resolved_igdb_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['storefront'], ['storefronts.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'storefront', 'external_id', name='uq_external_games_user_storefront_external')
    )
    # Add ownership_status separately with create_type=False so the existing
    # ownershipstatus enum is reused (op.add_column does not fire after_create).
    op.add_column('external_games',
        sa.Column('ownership_status', sa.Enum('OWNED', 'BORROWED', 'RENTED', 'SUBSCRIPTION', 'NO_LONGER_OWNED', name='ownershipstatus', create_type=False), nullable=True)
    )
    op.create_index(op.f('ix_external_games_storefront'), 'external_games', ['storefront'], unique=False)
    op.create_index(op.f('ix_external_games_user_id'), 'external_games', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_games_user_id'), table_name='external_games')
    op.drop_index(op.f('ix_external_games_storefront'), table_name='external_games')
    op.drop_table('external_games')
    # ### end Alembic commands ###
