"""add igdb_title field to steam_games table

Revision ID: 2076d9c0641d
Revises: a0800f9c86da
Create Date: 2025-08-15 09:33:50.758160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2076d9c0641d'
down_revision: Union[str, Sequence[str], None] = 'a0800f9c86da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_games', sa.Column('igdb_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steam_games', 'igdb_title')
    # ### end Alembic commands ###
