"""Add missing import framework fields to import_jobs table

Revision ID: 22921f6a27d9
Revises: 2076d9c0641d
Create Date: 2025-08-15 17:58:13.587498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22921f6a27d9'
down_revision: Union[str, Sequence[str], None] = '2076d9c0641d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing columns to import_jobs table
    op.add_column('import_jobs', sa.Column('source', sa.String(), nullable=True))
    op.add_column('import_jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('import_jobs', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_jobs', sa.Column('total_items', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_jobs', sa.Column('processed_items', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_jobs', sa.Column('successful_items', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_jobs', sa.Column('failed_items', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_jobs', sa.Column('error_message', sa.String(), nullable=True))
    op.create_index(op.f('ix_import_jobs_source'), 'import_jobs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove added columns from import_jobs table
    op.drop_index(op.f('ix_import_jobs_source'), table_name='import_jobs')
    op.drop_column('import_jobs', 'error_message')
    op.drop_column('import_jobs', 'failed_items')
    op.drop_column('import_jobs', 'successful_items')
    op.drop_column('import_jobs', 'processed_items')
    op.drop_column('import_jobs', 'total_items')
    op.drop_column('import_jobs', 'progress')
    op.drop_column('import_jobs', 'started_at')
    op.drop_column('import_jobs', 'source')
    # ### end Alembic commands ###
