"""Add copy-based architecture fields to darkadia_imports

Revision ID: 237cf47613e5
Revises: e1eb9faf589c
Create Date: 2025-08-21 10:00:49.634874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '237cf47613e5'
down_revision: Union[str, Sequence[str], None] = 'e1eb9faf589c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_game_platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('csv_row_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
        batch_op.add_column(sa.Column('copy_identifier', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('original_storefront_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('fallback_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('storefront_resolved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('requires_storefront_resolution', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_darkadia_imports_user_game_batch'), type_='unique')
        batch_op.create_index(batch_op.f('ix_darkadia_imports_game_name'), ['game_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_storefront_resolved'), ['storefront_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_user_game_platform_id'), ['user_game_platform_id'], unique=False)
        batch_op.create_unique_constraint('uq_darkadia_imports_user_row_batch', ['user_id', 'csv_row_number', 'batch_id'])
        batch_op.create_foreign_key('fk_darkadia_imports_user_game_platform_id', 'user_game_platforms', ['user_game_platform_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_darkadia_imports_user_game_platform_id', type_='foreignkey')
        batch_op.drop_constraint('uq_darkadia_imports_user_row_batch', type_='unique')
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_user_game_platform_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_storefront_resolved'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_game_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_darkadia_imports_user_game_batch'), ['user_id', 'user_game_id', 'batch_id'])
        batch_op.drop_column('requires_storefront_resolution')
        batch_op.drop_column('storefront_resolved')
        batch_op.drop_column('fallback_platform_name')
        batch_op.drop_column('original_storefront_name')
        batch_op.drop_column('copy_identifier')
        batch_op.drop_column('game_name')
        batch_op.drop_column('csv_row_number')
        batch_op.drop_column('user_game_platform_id')

    # ### end Alembic commands ###
