"""add auto_retry_done field to Job model

Revision ID: 257fba8125ad
Revises: 5e7b2602aa8d
Create Date: 2025-12-27 09:01:52.460574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '257fba8125ad'
down_revision: Union[str, Sequence[str], None] = '5e7b2602aa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('auto_retry_done', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'auto_retry_done')
    # ### end Alembic commands ###
