"""Add steam_games table for Steam library management

Revision ID: 2c7b6e5676cf
Revises: b329a9cda7cc
Create Date: 2025-08-07 06:45:35.612454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c7b6e5676cf'
down_revision: Union[str, Sequence[str], None] = 'b329a9cda7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('igdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['igdb_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'steam_appid', name='uq_steam_games_user_appid')
    )
    op.create_index(op.f('ix_steam_games_game_id'), 'steam_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_steam_games_igdb_id'), 'steam_games', ['igdb_id'], unique=False)
    op.create_index(op.f('ix_steam_games_steam_appid'), 'steam_games', ['steam_appid'], unique=False)
    op.create_index(op.f('ix_steam_games_user_id'), 'steam_games', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_games_user_id'), table_name='steam_games')
    op.drop_index(op.f('ix_steam_games_steam_appid'), table_name='steam_games')
    op.drop_index(op.f('ix_steam_games_igdb_id'), table_name='steam_games')
    op.drop_index(op.f('ix_steam_games_game_id'), table_name='steam_games')
    op.drop_table('steam_games')
    # ### end Alembic commands ###
