"""Add Steam import job tracking tables

Revision ID: 33ece1f68c49
Revises: e5f5bd9cc304
Create Date: 2025-08-05 11:33:06.944619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33ece1f68c49'
down_revision: Union[str, Sequence[str], None] = 'e5f5bd9cc304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_import_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'AWAITING_REVIEW', 'FINALIZING', 'COMPLETED', 'FAILED', name='steamimportjobstatus'), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('processed_games', sa.Integer(), nullable=False),
    sa.Column('matched_games', sa.Integer(), nullable=False),
    sa.Column('awaiting_review_games', sa.Integer(), nullable=False),
    sa.Column('skipped_games', sa.Integer(), nullable=False),
    sa.Column('imported_games', sa.Integer(), nullable=False),
    sa.Column('platform_added_games', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steam_library_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steam_import_jobs_status'), 'steam_import_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_steam_import_jobs_user_id'), 'steam_import_jobs', ['user_id'], unique=False)
    op.create_table('steam_import_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('import_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=False),
    sa.Column('steam_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('MATCHED', 'AWAITING_USER', 'SKIPPED', 'IMPORTED', 'PLATFORM_ADDED', 'ALREADY_OWNED', 'IMPORT_FAILED', name='steamimportgamestatus'), nullable=False),
    sa.Column('matched_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['steam_import_jobs.id'], ),
    sa.ForeignKeyConstraint(['matched_game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steam_import_games_import_job_id'), 'steam_import_games', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_steam_import_games_status'), 'steam_import_games', ['status'], unique=False)
    op.create_index(op.f('ix_steam_import_games_steam_appid'), 'steam_import_games', ['steam_appid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_import_games_steam_appid'), table_name='steam_import_games')
    op.drop_index(op.f('ix_steam_import_games_status'), table_name='steam_import_games')
    op.drop_index(op.f('ix_steam_import_games_import_job_id'), table_name='steam_import_games')
    op.drop_table('steam_import_games')
    op.drop_index(op.f('ix_steam_import_jobs_user_id'), table_name='steam_import_jobs')
    op.drop_index(op.f('ix_steam_import_jobs_status'), table_name='steam_import_jobs')
    op.drop_table('steam_import_jobs')
    # ### end Alembic commands ###
