"""Recreate darkadia_imports table with correct unique constraint

Revision ID: 576c6f19bbf9
Revises: 481842d92624
Create Date: 2025-08-26 08:27:50.175251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576c6f19bbf9'
down_revision: Union[str, Sequence[str], None] = '481842d92624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_darkadia_imports_user_row_batch'), type_='unique')
        batch_op.create_unique_constraint('uq_darkadia_imports_user_row_copy_batch', ['user_id', 'csv_row_number', 'copy_identifier', 'batch_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.drop_constraint('uq_darkadia_imports_user_row_copy_batch', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_darkadia_imports_user_row_batch'), ['user_id', 'csv_row_number', 'batch_id'])

    # ### end Alembic commands ###
