"""job task system refactor

Revision ID: 5e7b2602aa8d
Revises: a4078e2797b8
Create Date: 2025-12-25 19:24:38.942967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e7b2602aa8d'
down_revision: Union[str, Sequence[str], None] = 'a4078e2797b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('source_metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PENDING_REVIEW', 'SKIPPED', 'FAILED', name='jobitemstatus'), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('igdb_candidates_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_igdb_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'item_key', name='uq_job_item_key')
    )
    op.create_index(op.f('ix_job_items_item_key'), 'job_items', ['item_key'], unique=False)
    op.create_index(op.f('ix_job_items_job_id'), 'job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_items_status'), 'job_items', ['status'], unique=False)
    op.create_index(op.f('ix_job_items_user_id'), 'job_items', ['user_id'], unique=False)
    op.drop_index(op.f('ix_review_items_job_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_user_id'), table_name='review_items')
    op.drop_table('review_items')
    op.add_column('jobs', sa.Column('total_items', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_jobs_import_subtype'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_taskiq_task_id'), table_name='jobs')
    op.drop_constraint(op.f('fk_jobs_parent_job_id'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'successful_items')
    op.drop_column('jobs', 'import_subtype')
    op.drop_column('jobs', 'error_log')
    op.drop_column('jobs', 'failed_items')
    op.drop_column('jobs', 'taskiq_task_id')
    op.drop_column('jobs', 'progress_current')
    op.drop_column('jobs', 'parent_job_id')
    op.drop_column('jobs', 'processed_item_ids')
    op.drop_column('jobs', 'result_summary')
    op.drop_column('jobs', 'progress_total')
    op.drop_column('jobs', 'failed_item_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('failed_item_ids', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('progress_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('result_summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('processed_item_ids', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('parent_job_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('progress_current', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('taskiq_task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('failed_items', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('error_log', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('import_subtype', postgresql.ENUM('LIBRARY_IMPORT', 'AUTO_MATCH', 'BULK_SYNC', 'BULK_UNMATCH', 'BULK_UNSYNC', 'BULK_UNIGNORE', name='importjobsubtype'), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('successful_items', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_jobs_parent_job_id'), 'jobs', 'jobs', ['parent_job_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_jobs_taskiq_task_id'), 'jobs', ['taskiq_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_import_subtype'), 'jobs', ['import_subtype'], unique=False)
    op.drop_column('jobs', 'total_items')
    op.create_table('review_items',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'MATCHED', 'SKIPPED', 'REMOVAL', name='reviewitemstatus'), autoincrement=False, nullable=False),
    sa.Column('source_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('source_metadata', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('igdb_candidates', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resolved_igdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('review_items_job_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('review_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_items_pkey')),
    sa.UniqueConstraint('job_id', 'source_title', name=op.f('uq_review_items_job_source_title'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_review_items_user_id'), 'review_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    op.create_index(op.f('ix_review_items_job_id'), 'review_items', ['job_id'], unique=False)
    op.drop_index(op.f('ix_job_items_user_id'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_status'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_job_id'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_item_key'), table_name='job_items')
    op.drop_table('job_items')
    # ### end Alembic commands ###
