"""add game modes themes perspectives

Revision ID: 6305481a01cf
Revises: 0c863acf2282
Create Date: 2026-01-03 12:10:09.511828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6305481a01cf'
down_revision: Union[str, Sequence[str], None] = '0c863acf2282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_modes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('games', sa.Column('themes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('games', sa.Column('player_perspectives', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'player_perspectives')
    op.drop_column('games', 'themes')
    op.drop_column('games', 'game_modes')
    # ### end Alembic commands ###
