"""add ignored_external_games table

Revision ID: 6508079ee686
Revises: c50d1cb7244b
Create Date: 2025-12-15 18:37:43.806369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6508079ee686'
down_revision: Union[str, Sequence[str], None] = 'c50d1cb7244b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignored_external_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', postgresql.ENUM('STEAM', 'EPIC', 'GOG', 'DARKADIA', 'NEXORIOUS', 'SYSTEM', name='backgroundjobsource', create_type=False), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_ignored_external_games_user_source_external')
    )
    op.create_index(op.f('ix_ignored_external_games_external_id'), 'ignored_external_games', ['external_id'], unique=False)
    op.create_index(op.f('ix_ignored_external_games_source'), 'ignored_external_games', ['source'], unique=False)
    op.create_index(op.f('ix_ignored_external_games_user_id'), 'ignored_external_games', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ignored_external_games_user_id'), table_name='ignored_external_games')
    op.drop_index(op.f('ix_ignored_external_games_source'), table_name='ignored_external_games')
    op.drop_index(op.f('ix_ignored_external_games_external_id'), table_name='ignored_external_games')
    op.drop_table('ignored_external_games')
    # ### end Alembic commands ###
