"""initial schema

Revision ID: 72d8dfbc57f2
Revises:
Create Date: 2025-12-21 17:51:16.906072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "72d8dfbc57f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "developer", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "publisher", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column(
            "cover_art_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("rating_average", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("game_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("estimated_playtime_hours", sa.Integer(), nullable=True),
        sa.Column("howlongtobeat_main", sa.Integer(), nullable=True),
        sa.Column("howlongtobeat_extra", sa.Integer(), nullable=True),
        sa.Column("howlongtobeat_completionist", sa.Integer(), nullable=True),
        sa.Column(
            "igdb_slug", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "igdb_platform_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "igdb_platform_names", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_igdb_slug"), "games", ["igdb_slug"], unique=False)
    op.create_index(op.f("ix_games_title"), "games", ["title"], unique=False)
    op.create_table(
        "storefronts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "icon_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "base_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "version_added", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_storefronts_name"), "storefronts", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "password_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("preferences", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "ignored_external_games",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "STEAM",
                "EPIC",
                "GOG",
                "XBOX",
                "PLAYSTATION",
                "CSV",
                "NEXORIOUS",
                "SYSTEM",
                name="backgroundjobsource",
            ),
            nullable=False,
        ),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "source",
            "external_id",
            name="uq_ignored_external_games_user_source_external",
        ),
    )
    op.create_index(
        op.f("ix_ignored_external_games_external_id"),
        "ignored_external_games",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ignored_external_games_source"),
        "ignored_external_games",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ignored_external_games_user_id"),
        "ignored_external_games",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum("SYNC", "IMPORT", "EXPORT", name="backgroundjobtype"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "STEAM",
                "EPIC",
                "GOG",
                "XBOX",
                "PLAYSTATION",
                "CSV",
                "NEXORIOUS",
                "SYSTEM",
                name="backgroundjobsource",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "AWAITING_REVIEW",
                "READY",
                "FINALIZING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="backgroundjobstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "LOW", name="backgroundjobpriority"),
            nullable=False,
        ),
        sa.Column(
            "import_subtype",
            sa.Enum(
                "LIBRARY_IMPORT",
                "AUTO_MATCH",
                "BULK_SYNC",
                "BULK_UNMATCH",
                "BULK_UNSYNC",
                "BULK_UNIGNORE",
                name="importjobsubtype",
            ),
            nullable=True,
        ),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("successful_items", sa.Integer(), nullable=False),
        sa.Column("failed_items", sa.Integer(), nullable=False),
        sa.Column("result_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_log", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "error_message",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column(
            "processed_item_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "failed_item_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "taskiq_task_id",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_import_subtype"), "jobs", ["import_subtype"], unique=False
    )
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_source"), "jobs", ["source"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_jobs_taskiq_task_id"), "jobs", ["taskiq_task_id"], unique=False
    )
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    op.create_table(
        "platforms",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "icon_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "default_storefront_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "version_added", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_storefront_id"],
            ["storefronts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_platforms_name"), "platforms", ["name"], unique=True)
    op.create_table(
        "tags",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tag_user_name"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "user_games",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column(
            "ownership_status",
            sa.Enum(
                "OWNED",
                "BORROWED",
                "RENTED",
                "SUBSCRIPTION",
                "NO_LONGER_OWNED",
                name="ownershipstatus",
            ),
            nullable=False,
        ),
        sa.Column("personal_rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("is_loved", sa.Boolean(), nullable=False),
        sa.Column(
            "play_status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "MASTERED",
                "DOMINATED",
                "SHELVED",
                "REPLAY",
                name="playstatus",
            ),
            nullable=False,
        ),
        sa.Column("hours_played", sa.Integer(), nullable=False),
        sa.Column("personal_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("acquired_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "game_id", name="uq_user_games_user_game"),
    )
    op.create_index(
        op.f("ix_user_games_game_id"), "user_games", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_games_is_loved"), "user_games", ["is_loved"], unique=False
    )
    op.create_index(
        op.f("ix_user_games_play_status"), "user_games", ["play_status"], unique=False
    )
    op.create_index(
        op.f("ix_user_games_user_id"), "user_games", ["user_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "refresh_token_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_token_hash"),
        "user_sessions",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "user_sync_configs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "platform", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "frequency",
            sa.Enum("MANUAL", "HOURLY", "DAILY", "WEEKLY", name="syncfrequency"),
            nullable=False,
        ),
        sa.Column("auto_add", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sync_configs_platform"),
        "user_sync_configs",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sync_configs_user_id"),
        "user_sync_configs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "wishlists",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wishlists_game_id"), "wishlists", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_wishlists_user_id"), "wishlists", ["user_id"], unique=False
    )
    op.create_table(
        "platform_storefronts",
        sa.Column("platform_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storefront_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storefront_id"],
            ["storefronts.id"],
        ),
        sa.PrimaryKeyConstraint("platform_id", "storefront_id"),
        sa.UniqueConstraint(
            "platform_id", "storefront_id", name="uq_platform_storefront"
        ),
    )
    op.create_table(
        "review_items",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "MATCHED", "SKIPPED", "REMOVAL", name="reviewitemstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "source_title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "source_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "igdb_candidates", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("resolved_igdb_id", sa.Integer(), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id", "source_title", name="uq_review_items_job_source_title"
        ),
    )
    op.create_index(
        op.f("ix_review_items_job_id"), "review_items", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_items_status"), "review_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_review_items_user_id"), "review_items", ["user_id"], unique=False
    )
    op.create_table(
        "user_game_platforms",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("platform_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("storefront_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "store_game_id", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "store_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column(
            "original_platform_name",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storefront_id"],
            ["storefronts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_game_id"],
            ["user_games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_game_id",
            "platform_id",
            "storefront_id",
            name="uq_user_game_platform_storefront",
        ),
    )
    op.create_index(
        op.f("ix_user_game_platforms_platform_id"),
        "user_game_platforms",
        ["platform_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_game_platforms_user_game_id"),
        "user_game_platforms",
        ["user_game_id"],
        unique=False,
    )
    op.create_table(
        "user_game_tags",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_game_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tag_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_game_id"],
            ["user_games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_game_id", "tag_id", name="uq_user_game_tag"),
    )
    op.create_index(
        op.f("ix_user_game_tags_tag_id"), "user_game_tags", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_game_tags_user_game_id"),
        "user_game_tags",
        ["user_game_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_game_tags_user_game_id"), table_name="user_game_tags")
    op.drop_index(op.f("ix_user_game_tags_tag_id"), table_name="user_game_tags")
    op.drop_table("user_game_tags")
    op.drop_index(
        op.f("ix_user_game_platforms_user_game_id"), table_name="user_game_platforms"
    )
    op.drop_index(
        op.f("ix_user_game_platforms_platform_id"), table_name="user_game_platforms"
    )
    op.drop_table("user_game_platforms")
    op.drop_index(op.f("ix_review_items_user_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_status"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_job_id"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_table("platform_storefronts")
    op.drop_index(op.f("ix_wishlists_user_id"), table_name="wishlists")
    op.drop_index(op.f("ix_wishlists_game_id"), table_name="wishlists")
    op.drop_table("wishlists")
    op.drop_index(op.f("ix_user_sync_configs_user_id"), table_name="user_sync_configs")
    op.drop_index(op.f("ix_user_sync_configs_platform"), table_name="user_sync_configs")
    op.drop_table("user_sync_configs")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_token_hash"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_user_games_user_id"), table_name="user_games")
    op.drop_index(op.f("ix_user_games_play_status"), table_name="user_games")
    op.drop_index(op.f("ix_user_games_is_loved"), table_name="user_games")
    op.drop_index(op.f("ix_user_games_game_id"), table_name="user_games")
    op.drop_table("user_games")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_platforms_name"), table_name="platforms")
    op.drop_table("platforms")
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_taskiq_task_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_import_subtype"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        op.f("ix_ignored_external_games_user_id"), table_name="ignored_external_games"
    )
    op.drop_index(
        op.f("ix_ignored_external_games_source"), table_name="ignored_external_games"
    )
    op.drop_index(
        op.f("ix_ignored_external_games_external_id"),
        table_name="ignored_external_games",
    )
    op.drop_table("ignored_external_games")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_storefronts_name"), table_name="storefronts")
    op.drop_table("storefronts")
    op.drop_index(op.f("ix_games_title"), table_name="games")
    op.drop_index(op.f("ix_games_igdb_slug"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
