"""remove store_game_id and store_url from user_game_platforms

Revision ID: 73b3dbc0fd0c
Revises: c860aae6109b
Create Date: 2026-01-12 17:54:23.837833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b3dbc0fd0c'
down_revision: Union[str, Sequence[str], None] = 'c860aae6109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_platforms', 'store_url')
    op.drop_column('user_game_platforms', 'store_game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_platforms', sa.Column('store_game_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user_game_platforms', sa.Column('store_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
