"""Add resolved_storefront_id to darkadia_imports

Revision ID: 7b8f517ecfe3
Revises: 237cf47613e5
Create Date: 2025-08-24 13:15:05.109708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b8f517ecfe3'
down_revision: Union[str, Sequence[str], None] = '237cf47613e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_darkadia_imports_resolved_storefront_id', 'storefronts', ['resolved_storefront_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_darkadia_imports_resolved_storefront_id', type_='foreignkey')
        batch_op.drop_column('resolved_storefront_id')

    # ### end Alembic commands ###
