"""Initial migration without GameAlias

Revision ID: 82e3dd548c5f
Revises: 
Create Date: 2025-09-08 17:05:47.689972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82e3dd548c5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_art_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('game_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_playtime_hours', sa.Integer(), nullable=True),
    sa.Column('howlongtobeat_main', sa.Integer(), nullable=True),
    sa.Column('howlongtobeat_extra', sa.Integer(), nullable=True),
    sa.Column('howlongtobeat_completionist', sa.Integer(), nullable=True),
    sa.Column('igdb_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('igdb_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('igdb_platform_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('igdb_platform_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_igdb_id'), ['igdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_igdb_slug'), ['igdb_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_steam_appid'), ['steam_appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_title'), ['title'], unique=False)

    op.create_table('storefronts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version_added', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storefronts_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('darkadia_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('igdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('igdb_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('csv_data', sa.JSON(), nullable=True),
    sa.Column('transformation_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_darkadia_games_user_external')
    )
    with op.batch_alter_table('darkadia_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_darkadia_games_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_games_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_games_igdb_id'), ['igdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_games_user_id'), ['user_id'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('import_type', sa.Enum('CSV', 'STEAM', 'EPIC', 'GOG', 'XBOX', 'PLAYSTATION', 'DARKADIA', name='importtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='importstatus'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_log', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_type', sa.Enum('LIBRARY_IMPORT', 'AUTO_MATCH', 'BULK_SYNC', 'BULK_UNMATCH', 'BULK_UNSYNC', 'BULK_UNIGNORE', name='jobtype'), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('successful_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('platforms',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('default_storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version_added', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_storefront_id'], ['storefronts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_name'), ['name'], unique=True)

    op.create_table('steam_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('igdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('igdb_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'steam_appid', name='uq_steam_games_user_appid')
    )
    with op.batch_alter_table('steam_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steam_games_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_games_igdb_id'), ['igdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_games_steam_appid'), ['steam_appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_games_user_id'), ['user_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    op.create_table('user_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ownership_status', sa.Enum('OWNED', 'BORROWED', 'RENTED', 'SUBSCRIPTION', 'NO_LONGER_OWNED', name='ownershipstatus'), nullable=False),
    sa.Column('personal_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('is_loved', sa.Boolean(), nullable=False),
    sa.Column('play_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'MASTERED', 'DOMINATED', 'SHELVED', 'DROPPED', 'REPLAY', name='playstatus'), nullable=False),
    sa.Column('hours_played', sa.Integer(), nullable=False),
    sa.Column('personal_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_games_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_games_is_loved'), ['is_loved'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_games_play_status'), ['play_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_games_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('wishlists',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlists_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlists_user_id'), ['user_id'], unique=False)

    op.create_table('platform_storefronts',
    sa.Column('platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], ),
    sa.PrimaryKeyConstraint('platform_id', 'storefront_id'),
    sa.UniqueConstraint('platform_id', 'storefront_id', name='uq_platform_storefront')
    )
    op.create_table('user_game_platforms',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_game_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('store_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('original_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], ),
    sa.ForeignKeyConstraint(['user_game_id'], ['user_games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_game_id', 'platform_id', 'storefront_id', name='uq_user_game_platform_storefront')
    )
    with op.batch_alter_table('user_game_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_game_platforms_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_game_platforms_user_game_id'), ['user_game_id'], unique=False)

    op.create_table('user_game_tags',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_game_id'], ['user_games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_game_id', 'tag_id', name='uq_user_game_tag')
    )
    with op.batch_alter_table('user_game_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_game_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_game_tags_user_game_id'), ['user_game_id'], unique=False)

    op.create_table('darkadia_imports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_game_platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('csv_row_number', sa.Integer(), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('copy_identifier', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('csv_file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('import_timestamp', sa.DateTime(), nullable=False),
    sa.Column('original_csv_data', sa.JSON(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('playing', sa.Boolean(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('dominated', sa.Boolean(), nullable=False),
    sa.Column('shelved', sa.Boolean(), nullable=False),
    sa.Column('physical_copy_data', sa.JSON(), nullable=True),
    sa.Column('original_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('original_storefront_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('fallback_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('platform_resolved', sa.Boolean(), nullable=False),
    sa.Column('storefront_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_storefront_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_storefront_resolution', sa.Boolean(), nullable=False),
    sa.Column('platform_resolution_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['resolved_storefront_id'], ['storefronts.id'], ),
    sa.ForeignKeyConstraint(['user_game_id'], ['user_games.id'], ),
    sa.ForeignKeyConstraint(['user_game_platform_id'], ['user_game_platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'csv_row_number', 'copy_identifier', 'batch_id', name='uq_darkadia_imports_user_row_copy_batch')
    )
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_darkadia_imports_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_game_name'), ['game_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_import_timestamp'), ['import_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_platform_resolved'), ['platform_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_storefront_resolved'), ['storefront_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_user_game_id'), ['user_game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_user_game_platform_id'), ['user_game_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_imports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_user_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_user_game_platform_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_user_game_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_storefront_resolved'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_platform_resolved'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_import_timestamp'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_game_name'))
        batch_op.drop_index(batch_op.f('ix_darkadia_imports_batch_id'))

    op.drop_table('darkadia_imports')
    with op.batch_alter_table('user_game_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_game_tags_user_game_id'))
        batch_op.drop_index(batch_op.f('ix_user_game_tags_tag_id'))

    op.drop_table('user_game_tags')
    with op.batch_alter_table('user_game_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_game_platforms_user_game_id'))
        batch_op.drop_index(batch_op.f('ix_user_game_platforms_platform_id'))

    op.drop_table('user_game_platforms')
    op.drop_table('platform_storefronts')
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlists_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlists_game_id'))

    op.drop_table('wishlists')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_games_play_status'))
        batch_op.drop_index(batch_op.f('ix_user_games_is_loved'))
        batch_op.drop_index(batch_op.f('ix_user_games_game_id'))

    op.drop_table('user_games')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))

    op.drop_table('tags')
    with op.batch_alter_table('steam_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steam_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_steam_games_steam_appid'))
        batch_op.drop_index(batch_op.f('ix_steam_games_igdb_id'))
        batch_op.drop_index(batch_op.f('ix_steam_games_game_id'))

    op.drop_table('steam_games')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_name'))

    op.drop_table('platforms')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_source'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('darkadia_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_darkadia_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_games_igdb_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_games_game_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_games_external_id'))

    op.drop_table('darkadia_games')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storefronts_name'))

    op.drop_table('storefronts')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_title'))
        batch_op.drop_index(batch_op.f('ix_games_steam_appid'))
        batch_op.drop_index(batch_op.f('ix_games_igdb_slug'))
        batch_op.drop_index(batch_op.f('ix_games_igdb_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
