"""drop steam_games table

Revision ID: 86fa0cc8e50c
Revises: d72cc8054c2d
Create Date: 2025-12-15 19:36:29.951545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86fa0cc8e50c'
down_revision: Union[str, Sequence[str], None] = 'd72cc8054c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_games_igdb_id'), table_name='steam_games')
    op.drop_index(op.f('ix_steam_games_steam_appid'), table_name='steam_games')
    op.drop_index(op.f('ix_steam_games_user_id'), table_name='steam_games')
    op.drop_table('steam_games')
    op.drop_table('taskiq_messages')
    op.drop_index(op.f('taskiq_results_task_id_idx'), table_name='taskiq_results', postgresql_using='hash')
    op.drop_table('taskiq_results')
    op.create_unique_constraint('uq_platform_storefront', 'platform_storefronts', ['platform_id', 'storefront_id'])
    op.drop_constraint(op.f('uq_user_sync_config_user_platform'), 'user_sync_configs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_sync_config_user_platform'), 'user_sync_configs', ['user_id', 'platform'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_platform_storefront', 'platform_storefronts', type_='unique')
    op.create_table('taskiq_results',
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('task_id', name=op.f('taskiq_results_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('taskiq_results_task_id_idx'), 'taskiq_results', ['task_id'], unique=False, postgresql_using='hash')
    op.create_table('taskiq_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('taskiq_messages_pkey'))
    )
    op.create_table('steam_games',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('steam_appid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('igdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('igdb_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ignored', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('steam_games_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('steam_games_pkey')),
    sa.UniqueConstraint('user_id', 'steam_appid', name=op.f('uq_steam_games_user_appid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_steam_games_user_id'), 'steam_games', ['user_id'], unique=False)
    op.create_index(op.f('ix_steam_games_steam_appid'), 'steam_games', ['steam_appid'], unique=False)
    op.create_index(op.f('ix_steam_games_igdb_id'), 'steam_games', ['igdb_id'], unique=False)
    # ### end Alembic commands ###
