"""add hours_played to user_game_platforms

Revision ID: 972c3d4ae063
Revises: fca95df40fe1
Create Date: 2025-12-31 18:41:48.466922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '972c3d4ae063'
down_revision: Union[str, Sequence[str], None] = 'fca95df40fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_platforms', sa.Column('hours_played', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_platforms', 'hours_played')
    # ### end Alembic commands ###
