"""add last_updated field to games table for IGDB metadata refresh tracking

Revision ID: a0800f9c86da
Revises: ac755955f22b
Create Date: 2025-08-13 21:31:23.035244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0800f9c86da'
down_revision: Union[str, Sequence[str], None] = 'ac755955f22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_constraint(None, 'steam_games', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'steam_games', 'games', ['igdb_id'], ['id'])
    op.drop_column('games', 'last_updated')
    # ### end Alembic commands ###
