"""add parent_job_id to jobs table

Revision ID: a4078e2797b8
Revises: 72d8dfbc57f2
Create Date: 2025-12-25 12:01:24.849313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4078e2797b8'
down_revision: Union[str, Sequence[str], None] = '72d8dfbc57f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('parent_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_foreign_key('fk_jobs_parent_job_id', 'jobs', 'jobs', ['parent_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_parent_job_id', 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_column('jobs', 'parent_job_id')
    # ### end Alembic commands ###
