"""add external_games table and user_game_platform fields

Revision ID: b11eb1881c9a
Revises: 16859bc970d4
Create Date: 2026-01-12 16:50:35.646632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b11eb1881c9a'
down_revision: Union[str, Sequence[str], None] = '16859bc970d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storefront', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('resolved_igdb_id', sa.Integer(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('playtime_hours', sa.Integer(), nullable=False),
    sa.Column('ownership_status', postgresql.ENUM('OWNED', 'BORROWED', 'RENTED', 'SUBSCRIPTION', 'NO_LONGER_OWNED', name='ownershipstatus', create_type=False), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform'], ['platforms.name'], ),
    sa.ForeignKeyConstraint(['resolved_igdb_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['storefront'], ['storefronts.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'storefront', 'external_id', name='uq_external_games_user_storefront_external')
    )
    op.create_index(op.f('ix_external_games_external_id'), 'external_games', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_games_is_available'), 'external_games', ['is_available'], unique=False)
    op.create_index(op.f('ix_external_games_is_skipped'), 'external_games', ['is_skipped'], unique=False)
    op.create_index(op.f('ix_external_games_resolved_igdb_id'), 'external_games', ['resolved_igdb_id'], unique=False)
    op.create_index(op.f('ix_external_games_storefront'), 'external_games', ['storefront'], unique=False)
    op.create_index(op.f('ix_external_games_user_id'), 'external_games', ['user_id'], unique=False)
    op.add_column('user_game_platforms', sa.Column('external_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_game_platforms', sa.Column('sync_from_source', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_game_platforms_external_game_id'), 'user_game_platforms', ['external_game_id'], unique=False)
    op.create_foreign_key(None, 'user_game_platforms', 'external_games', ['external_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_game_platforms', type_='foreignkey')
    op.drop_index(op.f('ix_user_game_platforms_external_game_id'), table_name='user_game_platforms')
    op.drop_column('user_game_platforms', 'sync_from_source')
    op.drop_column('user_game_platforms', 'external_game_id')
    op.drop_index(op.f('ix_external_games_user_id'), table_name='external_games')
    op.drop_index(op.f('ix_external_games_storefront'), table_name='external_games')
    op.drop_index(op.f('ix_external_games_resolved_igdb_id'), table_name='external_games')
    op.drop_index(op.f('ix_external_games_is_skipped'), table_name='external_games')
    op.drop_index(op.f('ix_external_games_is_available'), table_name='external_games')
    op.drop_index(op.f('ix_external_games_external_id'), table_name='external_games')
    op.drop_table('external_games')
    # ### end Alembic commands ###
