"""Add UserSyncConfig model

Revision ID: c50d1cb7244b
Revises: 43a952803c16
Create Date: 2025-12-14 16:31:49.732258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c50d1cb7244b'
down_revision: Union[str, Sequence[str], None] = '43a952803c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sync_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('frequency', sa.Enum('MANUAL', 'HOURLY', 'DAILY', 'WEEKLY', name='syncfrequency'), nullable=False),
    sa.Column('auto_add', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sync_configs_platform'), 'user_sync_configs', ['platform'], unique=False)
    op.create_index(op.f('ix_user_sync_configs_user_id'), 'user_sync_configs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_sync_config_user_platform', 'user_sync_configs', ['user_id', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_sync_config_user_platform', 'user_sync_configs', type_='unique')
    op.drop_index(op.f('ix_user_sync_configs_user_id'), table_name='user_sync_configs')
    op.drop_index(op.f('ix_user_sync_configs_platform'), table_name='user_sync_configs')
    op.drop_table('user_sync_configs')
    # ### end Alembic commands ###
