"""Add resolved_platform_id to darkadia_imports

Revision ID: cae5f24aa10c
Revises: 63c2a5c51259
Create Date: 2025-09-04 16:52:22.466954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cae5f24aa10c'
down_revision: Union[str, Sequence[str], None] = '63c2a5c51259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_platform_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_darkadia_imports_resolved_platform_id', 'platforms', ['resolved_platform_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_imports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_darkadia_imports_resolved_platform_id', type_='foreignkey')
        batch_op.drop_column('resolved_platform_id')

    # ### end Alembic commands ###
