"""add unique constraint to user_games user_id game_id

Revision ID: db3b6ae1746c
Revises: 45b4106a1286
Create Date: 2025-12-19 19:49:16.448285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db3b6ae1746c'
down_revision: Union[str, Sequence[str], None] = '45b4106a1286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, handle duplicate user_game entries
    # Strategy: Identify duplicates to keep, delete related records from duplicates to remove, then delete duplicate user_games

    # Identify duplicate user_games: keep the oldest (MIN(id)), delete the rest
    # Step 1: Delete user_game_platforms associated with duplicate user_games (not the kept one)
    op.execute("""
        DELETE FROM user_game_platforms
        WHERE user_game_id IN (
            SELECT ug.id
            FROM user_games ug
            INNER JOIN (
                SELECT user_id, game_id, MIN(id) as kept_id
                FROM user_games
                GROUP BY user_id, game_id
                HAVING COUNT(*) > 1
            ) dups ON ug.user_id = dups.user_id AND ug.game_id = dups.game_id
            WHERE ug.id != dups.kept_id
        )
    """)

    # Step 2: Delete user_game_tags associated with duplicate user_games (not the kept one)
    op.execute("""
        DELETE FROM user_game_tags
        WHERE user_game_id IN (
            SELECT ug.id
            FROM user_games ug
            INNER JOIN (
                SELECT user_id, game_id, MIN(id) as kept_id
                FROM user_games
                GROUP BY user_id, game_id
                HAVING COUNT(*) > 1
            ) dups ON ug.user_id = dups.user_id AND ug.game_id = dups.game_id
            WHERE ug.id != dups.kept_id
        )
    """)

    # Step 3: Delete darkadia_imports associated with duplicate user_games (not the kept one)
    op.execute("""
        DELETE FROM darkadia_imports
        WHERE user_game_id IN (
            SELECT ug.id
            FROM user_games ug
            INNER JOIN (
                SELECT user_id, game_id, MIN(id) as kept_id
                FROM user_games
                GROUP BY user_id, game_id
                HAVING COUNT(*) > 1
            ) dups ON ug.user_id = dups.user_id AND ug.game_id = dups.game_id
            WHERE ug.id != dups.kept_id
        )
    """)

    # Step 4: Remove duplicate user_game entries (keep oldest by id)
    op.execute("""
        DELETE FROM user_games
        WHERE id IN (
            SELECT ug.id
            FROM user_games ug
            INNER JOIN (
                SELECT user_id, game_id, MIN(id) as kept_id
                FROM user_games
                GROUP BY user_id, game_id
                HAVING COUNT(*) > 1
            ) dups ON ug.user_id = dups.user_id AND ug.game_id = dups.game_id
            WHERE ug.id != dups.kept_id
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_games_user_game', 'user_games', ['user_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_games_user_game', 'user_games', type_='unique')
    # ### end Alembic commands ###
