"""Add external_game_id and sync_from_source to user_game_platforms

Revision ID: dc09220836f0
Revises: 1531bea008ab
Create Date: 2026-02-28 19:22:02.526377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc09220836f0'
down_revision: Union[str, Sequence[str], None] = '1531bea008ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_platforms', sa.Column('external_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_game_platforms', sa.Column('sync_from_source', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_game_platforms_external_game_id'), 'user_game_platforms', ['external_game_id'], unique=False)
    op.create_foreign_key(None, 'user_game_platforms', 'external_games', ['external_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_game_platforms', type_='foreignkey')
    op.drop_index(op.f('ix_user_game_platforms_external_game_id'), table_name='user_game_platforms')
    op.drop_column('user_game_platforms', 'sync_from_source')
    op.drop_column('user_game_platforms', 'external_game_id')
    # ### end Alembic commands ###
