"""Add darkadia_games staging table

Revision ID: ddda11c4e799
Revises: e3bfc686e3e4
Create Date: 2025-08-18 16:39:46.227055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ddda11c4e799'
down_revision: Union[str, Sequence[str], None] = 'e3bfc686e3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('darkadia_games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('igdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('igdb_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('csv_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_darkadia_games_user_external')
    )
    with op.batch_alter_table('darkadia_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_darkadia_games_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_games_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_games_igdb_id'), ['igdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_darkadia_games_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_darkadia_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_games_igdb_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_games_game_id'))
        batch_op.drop_index(batch_op.f('ix_darkadia_games_external_id'))

    op.drop_table('darkadia_games')
    # ### end Alembic commands ###
