"""make platform_id nullable and add original_platform_name to UserGamePlatform

Revision ID: e1eb9faf589c
Revises: fe03cebb9830
Create Date: 2025-08-20 21:04:02.808201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1eb9faf589c'
down_revision: Union[str, Sequence[str], None] = 'fe03cebb9830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.alter_column('platform_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_platforms', schema=None) as batch_op:
        batch_op.alter_column('platform_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('original_platform_name')

    # ### end Alembic commands ###
