"""add transformation_data to darkadia_games

Revision ID: e2446aac683d
Revises: ddda11c4e799
Create Date: 2025-08-19 09:04:15.984096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2446aac683d'
down_revision: Union[str, Sequence[str], None] = 'ddda11c4e799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('darkadia_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transformation_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.Enum('LIBRARY_IMPORT', 'AUTO_MATCH', 'BULK_SYNC', 'BULK_UNMATCH', 'BULK_UNSYNC', 'BULK_UNIGNORE', name='jobtype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('job_type')

    with op.batch_alter_table('darkadia_games', schema=None) as batch_op:
        batch_op.drop_column('transformation_data')

    # ### end Alembic commands ###
