"""add darkadia imports table

Revision ID: e3bfc686e3e4
Revises: 26b1fca8c8a1
Create Date: 2025-08-18 13:54:30.494329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3bfc686e3e4'
down_revision: Union[str, Sequence[str], None] = '26b1fca8c8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('darkadia_imports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('csv_file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('import_timestamp', sa.DateTime(), nullable=False),
    sa.Column('original_csv_data', sa.JSON(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('playing', sa.Boolean(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('dominated', sa.Boolean(), nullable=False),
    sa.Column('shelved', sa.Boolean(), nullable=False),
    sa.Column('physical_copy_data', sa.JSON(), nullable=True),
    sa.Column('original_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('platform_resolved', sa.Boolean(), nullable=False),
    sa.Column('platform_resolution_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_game_id'], ['user_games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'user_game_id', 'batch_id', name='uq_darkadia_imports_user_game_batch')
    )
    op.create_index(op.f('ix_darkadia_imports_batch_id'), 'darkadia_imports', ['batch_id'], unique=False)
    op.create_index(op.f('ix_darkadia_imports_import_timestamp'), 'darkadia_imports', ['import_timestamp'], unique=False)
    op.create_index(op.f('ix_darkadia_imports_platform_resolved'), 'darkadia_imports', ['platform_resolved'], unique=False)
    op.create_index(op.f('ix_darkadia_imports_user_game_id'), 'darkadia_imports', ['user_game_id'], unique=False)
    op.create_index(op.f('ix_darkadia_imports_user_id'), 'darkadia_imports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_darkadia_imports_user_id'), table_name='darkadia_imports')
    op.drop_index(op.f('ix_darkadia_imports_user_game_id'), table_name='darkadia_imports')
    op.drop_index(op.f('ix_darkadia_imports_platform_resolved'), table_name='darkadia_imports')
    op.drop_index(op.f('ix_darkadia_imports_import_timestamp'), table_name='darkadia_imports')
    op.drop_index(op.f('ix_darkadia_imports_batch_id'), table_name='darkadia_imports')
    op.drop_table('darkadia_imports')
    # ### end Alembic commands ###
