"""add backup_config table

Revision ID: f40c6a59ff67
Revises: f7326f86754b
Create Date: 2025-12-29 09:36:53.824794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f40c6a59ff67'
down_revision: Union[str, Sequence[str], None] = 'f7326f86754b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.Enum('MANUAL', 'DAILY', 'WEEKLY', name='backupschedule'), nullable=False),
    sa.Column('schedule_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('schedule_day', sa.Integer(), nullable=True),
    sa.Column('retention_mode', sa.Enum('DAYS', 'COUNT', name='retentionmode'), nullable=False),
    sa.Column('retention_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: uq_platform_storefront constraint already exists in database, removed from autogenerate
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_config')
    # NOTE: uq_platform_storefront constraint was not created in upgrade, so not dropping here
    # ### end Alembic commands ###
