"""add original_storefront_name to user_game_platforms

Revision ID: f772653ec5a4
Revises: 5fc9ec31f32e
Create Date: 2026-01-04 10:50:14.713305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f772653ec5a4'
down_revision: Union[str, Sequence[str], None] = '5fc9ec31f32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_platforms', sa.Column('original_storefront_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_platforms', 'original_storefront_name')
    # ### end Alembic commands ###
