#!/usr/bin/env bash
# Regenerate and verify internal/db/migrations/20260620000001_baseline.up.sql
# from the frozen v0.17.1 migration set. Idempotent; safe to re-run.
#
# Requires: docker (postgres:18-alpine; pg_dump runs INSIDE the container so its
# version always matches the runtime — never the host pg_dump).
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
FIX="$REPO/internal/migrate/testdata/v0_17_1"
OUT="$REPO/internal/db/migrations/20260620000001_baseline.up.sql"
SEED_TABLES=(platforms storefronts platform_storefronts backup_config)

start_pg() {  # $1 = db name → echoes container id
  local db="$1"
  local cid
  cid=$(docker run -d --rm -e POSTGRES_PASSWORD=t -e POSTGRES_USER=t -e POSTGRES_DB="$db" postgres:18-alpine)
  for _ in $(seq 1 30); do docker exec "$cid" pg_isready -U t >/dev/null 2>&1 && break; sleep 1; done
  echo "$cid"
}

apply_v0171() {  # $1 = cid, $2 = db
  for f in "$FIX"/*.up.sql; do
    docker exec -i "$1" psql -v ON_ERROR_STOP=1 -U t -d "$2" < "$f" >/dev/null
  done
}

# dump_schema strips owner/privilege/SET/COMMENT/extension noise, drops the
# bun_migrations + river_* tables, and normalizes for a stable byte comparison.
dump_schema() {  # $1 = cid, $2 = db
  docker exec "$1" pg_dump -U t -d "$2" \
    --schema-only --no-owner --no-privileges --no-comments \
    --exclude-table=bun_migrations --exclude-table='river_*' \
  | grep -vE '^(SET|SELECT pg_catalog\.set_config|--|$)' \
  | grep -vE '^(CREATE EXTENSION|COMMENT ON EXTENSION)' \
  | grep -vE '^\\(restrict|unrestrict) '
}

dump_seed() {  # $1 = cid, $2 = db
  local args=()
  for t in "${SEED_TABLES[@]}"; do args+=(-t "$t"); done
  docker exec "$1" pg_dump -U t -d "$2" --data-only --no-owner --no-privileges \
    --inserts --rows-per-insert=1 "${args[@]}" \
  | grep -vE '^(SET|SELECT pg_catalog\.set_config|--|$)' \
  | grep -vE '^\\(restrict|unrestrict) ' \
  | sed "s/^INSERT INTO public\.backup_config VALUES (\([0-9]*\), '\([^']*\)', '\([^']*\)', \([0-9]*\), .*);$/INSERT INTO public.backup_config (id, schedule_cron, retention_mode, retention_value) VALUES (\1, '\2', '\3', \4);/"
}

echo "==> Building v0.17.1 end-state DB"
CID_A=$(start_pg src)
trap 'docker stop "$CID_A" >/dev/null 2>&1 || true' EXIT
apply_v0171 "$CID_A" src

echo "==> Assembling $OUT"
{
  echo "-- Baseline schema (squashed from the v0.17.1 migration set; see issue #1117)."
  echo "-- Generated by scripts/gen-baseline.sh — do not hand-edit; regenerate instead."
  dump_schema "$CID_A" src
  echo
  echo "-- Seed/reference data (platforms, storefronts, platform_storefronts, backup_config)."
  dump_seed "$CID_A" src
} > "$OUT"

echo "==> Acceptance: baseline-only DB must match v0.17.1 byte-for-byte (schema)"
CID_B=$(start_pg dst)
trap 'docker stop "$CID_A" "$CID_B" >/dev/null 2>&1 || true' EXIT
docker exec -i "$CID_B" psql -v ON_ERROR_STOP=1 -U t -d dst < "$OUT" >/dev/null

if diff <(dump_schema "$CID_A" src) <(dump_schema "$CID_B" dst); then
  echo "    SCHEMA OK (identical)"
else
  echo "    SCHEMA MISMATCH — see diff above"; exit 1
fi

echo "==> Acceptance: seed data must match for all 4 tables"
for t in "${SEED_TABLES[@]}"; do
  ca=$(docker exec "$CID_A" psql -tA -U t -d src -c "SELECT count(*) FROM $t")
  cb=$(docker exec "$CID_B" psql -tA -U t -d dst -c "SELECT count(*) FROM $t")
  if [ "$ca" != "$cb" ]; then echo "    $t row count differs: $ca vs $cb"; exit 1; fi
  echo "    $t: $ca rows OK"
done
if diff <(dump_seed "$CID_A" src) <(dump_seed "$CID_B" dst); then
  echo "    SEED DATA OK (identical)"
else
  echo "    SEED DATA MISMATCH — see diff above"; exit 1
fi

echo "==> All acceptance checks passed."
