---
name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0/12 * * *" # run twice per day

jobs:
  auto-upgrade-flake-lock:
    runs-on: nexorious-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          planner: linux-multi
          init: none

      - name: Update flake.lock
        run: |
          nix flake update

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          # Add all changes
          git add .

          # Create commit message
          git commit -m "chore: update flake"

          # Push to main branch
          git push origin main
